version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - sudo yum install docker-ce  -y
      - sudo yum install -y yum-utils device-mapper-persistent-data lvm2
      - sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      - sudo systemctl enable docker.service
      - sudo systemctl start docker.service



  pre_build:
    commands:
      - echo "hello"
  build:
    commands:
      - docker images
      - docker run -t owasp/zap2docker-weekly zap-baseline.py -t https://1idcwzr8bi.execute-api.us-east-2.amazonaws.com/prod
