version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - sudo amazon-linux-extras install docker -y
      - sudo service docker start



  pre_build:
    commands:
      - echo "hello"
  build:
    commands:
      - docker images
      - docker run -t owasp/zap2docker-weekly zap-baseline.py -t https://243gvx5a47.execute-api.us-east-2.amazonaws.com/prod
