version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install docker-ce docker-ce-cli containerd.io  -y
      - apt-cache madison docker-ce
      - sudo apt-get install docker-ce=<VERSION_STRING> docker-ce-cli=<VERSION_STRING> containerd.io


  pre_build:
    commands:
      - echo "hello"
  build:
    commands:
      - docker images
      - docker run -t owasp/zap2docker-weekly zap-baseline.py -t https://243gvx5a47.execute-api.us-east-2.amazonaws.com/prod
