version: 0.2

env:
  variables:
    key: codebuild23

phases:
  install:
    runtime-versions:
      docker: 18
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - yum install -y jq


  build:
    commands:
      - echo Build started on `date` from dir `pwd`
   
      
  post_build:
    commands:
      - echo Build completed on `date`
      - docker run -t owasp/zap2docker-weekly zap-baseline.py -t https://243gvx5a47.execute-api.us-east-2.amazonaws.com/prod 
